"""empty message

Revision ID: 465f62ae331f
Revises: ad810600497a
Create Date: 2023-09-25 12:51:07.753894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '465f62ae331f'
down_revision = 'ad810600497a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('name')

    # ### end Alembic commands ###
